# permissions for end users to view aeroclustermanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aeroclustermanager-viewer-role
rules:
- apiGroups:
  - aerostation.aerospike.com
  resources:
  - aeroclustermanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aerostation.aerospike.com
  resources:
  - aeroclustermanagers/status
  verbs:
  - get
