# permissions for end users to edit aeroclustermanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aeroclustermanager-editor-role
rules:
- apiGroups:
  - aerostation.aerospike.com
  resources:
  - aeroclustermanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aerostation.aerospike.com
  resources:
  - aeroclustermanagers/status
  verbs:
  - get
