name: pr-integration-tests
on:
  pull_request:
    branches: 
    - main 

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: capi-api Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: localhost:5000
          ECR_REPOSITORY: capi-api
          IMAGE_TAG: 0.0.1
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f capi-api.dockerfile .
      - name: controller - Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: localhost:5000
          ECR_REPOSITORY: aerostation-capi-controller
          IMAGE_TAG: 0.0.1
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
      - name: api-server - Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: localhost:5000
          ECR_REPOSITORY: api-server
          IMAGE_TAG: 0.0.1
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f api-server.dockerfile .
