name: pr-linting
on:
  pull_request:
    branches: 
    - main 

jobs:
  golint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint-aerostation
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.42
          # Optional: working directory, useful for monorepos
          args: --timeout 3m0s --verbose --skip-dirs "api/v1alpha1,api/v1"
