name: pr-unit-tests
'on':
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          go-version: 1.17
      - name: run tests
        run: make test
