name: pr-unit-tests
'on':
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: arnested/go-version-action@v1
      id: versions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install go
      uses: actions/setup-go@v2
    - name: run tests
      run: make test
