name: pr-unit-tests
'on':
  pull_request:
    branches:
      - master
jobs:
  go-versions:
    name: Lookup go versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.versions.outputs.matrix }}
    steps:
    - uses: actions/checkout@v2
    - uses: arnested/go-version-action@v1
      id: versions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install go
        uses: actions/setup-go@v2
      - name: run tests
        run: make test
